services:
  postgres:
    image: postgres:15
    container_name: logezy-postgres
    restart: always
    environment:
      POSTGRES_USER: logezyuser
      POSTGRES_PASSWORD: logezypassword
      POSTGRES_DB: logezy_dev
    ports:
      - "5432:5432"
    volumes:
      - logezypgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logezyuser -d logezy_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  logezypgdata:
